from pathlib import Path

PROJECT_PATH = Path(__file__).parents[1].resolve()  # Raiz del proyecto
UTILS_PATH = PROJECT_PATH / "utils"
DATA_PATH = UTILS_PATH / "data"  # Ruta donde se almacena los datos
SRC_PATH = PROJECT_PATH / "src"  # Ruta de funciones
STREAMLIT_PATH = PROJECT_PATH / "streamlit"  # App Streamlit

# BASES
BASE =  DATA_PATH / 'Base_Elecciones.zip'
ELECTORES_PATH = DATA_PATH / "ELECTORES.csv"

# Lista de municipios del AMBA (Provincia de Buenos Aires)
MUNICIPIOS_AMBA = [
    # Conurbano Bonaerense y zona metropolitana (sin incluir CABA)
    "ALMIRANTE BROWN",
    "AVELLANEDA",
    "BERAZATEGUI",
    "BERISSO",
    "BRANDSEN",
    "CAMPANA",
    "CAÑUELAS",
    "ENSENADA",
    "ESCOBAR",
    "ESTEBAN ECHEVERRIA",
    "EXALTACION DE LA CRUZ",
    "EZEIZA",
    "FLORENCIO VARELA",
    "GENERAL LAS HERAS",
    "GENERAL RODRIGUEZ",
    "GENERAL SAN MARTIN",
    "HURLINGHAM",
    "ITUZAINGO",
    "JOSE C. PAZ",
    "LA MATANZA",
    "LANUS",
    "LA PLATA",
    "LOMAS DE ZAMORA",
    "LUJAN",
    "MARCOS PAZ",
    "MALVINAS ARGENTINAS",
    "MERLO",
    "MORENO",
    "MORON",
    "PILAR",
    "PRESIDENTE PERON",
    "QUILMES",
    "SAN FERNANDO",
    "SAN ISIDRO",
    "SAN MIGUEL",
    "SAN VICENTE",
    "TIGRE",
    "TRES DE FEBRERO",
    "VICENTE LOPEZ",
    "ZARATE",
]

# Diccionario que asigna a cada sección sus municipios
SECCION_MUNICIPIOS = {   'Sección Capital': ['LA PLATA'],
    'Sección Cuarta': [   'ALBERTI',
                          'BRAGADO',
                          'CARLOS CASARES',
                          'CARLOS TEJEDOR',
                          'CHACABUCO',
                          'CHIVILCOY',
                          'FLORENTINO AMEGHINO',
                          'GENERAL ARENALES',
                          'GENERAL PINTO',
                          'GENERAL VIAMONTE',
                          'GENERAL VILLEGAS',
                          'HIPOLITO YRIGOYEN',
                          'JUNIN',
                          'LEANDRO N. ALEM',
                          'LINCOLN',
                          'NUEVE DE JULIO',
                          'PEHUAJO',
                          'RIVADAVIA',
                          'TRENQUE LAUQUEN'],
    'Sección Primera': [   'DEL PILAR',
                           'CAMPANA',
                           'ESCOBAR',
                           'GENERAL LAS HERAS',
                           'GENERAL RODRIGUEZ',
                           'GENERAL SAN MARTIN',
                           'HURLINGHAM',
                           'ITUZAINGO',
                           'JOSE C. PAZ',
                           'LUJAN',
                           'MALVINAS ARGENTINAS',
                           'MARCOS PAZ',
                           'MERCEDES',
                           'MERLO',
                           'MORENO',
                           'MORON',
                           'NAVARRO',
                           'PILAR',
                           'SAN FERNANDO',
                           'SAN ISIDRO',
                           'SAN MIGUEL',
                           'SUIPACHA',
                           'TIGRE',
                           'TRES DE FEBRERO',
                           'VICENTE LOPEZ'],
    'Sección Quinta': [   'PARTIDO DE VILLA GESELL',
                          'PARTIDO DE PINAMAR',
                          'PARTIDO DE LA COSTA',
                          'GENERAL MADARIAGA',
                          'AYACUCHO',
                          'BALCARCE',
                          'CASTELLI',
                          'CHASCOMUS',
                          'DOLORES',
                          'GENERAL ALVARADO',
                          'GENERAL BELGRANO',
                          'GENERAL GUIDO',
                          'GENERAL JUAN MADARIAGA',
                          'GENERAL LAVALLE',
                          'GENERAL PAZ',
                          'GENERAL PUEYRREDON',
                          'LA COSTA',
                          'LAS FLORES',
                          'LEZAMA',
                          'LOBERIA',
                          'MAIPU',
                          'MAR CHIQUITA',
                          'MONTE',
                          'NECOCHEA',
                          'PILA',
                          'PINAMAR',
                          'RAUCH',
                          'SAN CAYETANO',
                          'TANDIL',
                          'TORDILLO',
                          'VILLA GESELL'],
    'Sección Segunda': [   'ARRECIFES',
                           'BARADERO',
                           'CAPITAN SARMIENTO',
                           'CARMEN DE ARECO',
                           'COLON',
                           'EXALTACION DE LA CRUZ',
                           'PERGAMINO',
                           'RAMALLO',
                           'ROJAS',
                           'SALTO',
                           'SAN ANDRES DE GILES',
                           'SAN ANTONIO DE ARECO',
                           'SAN NICOLAS',
                           'SAN PEDRO',
                           'ZARATE'],
    'Sección Sexta': [   'ADOLFO ALSINA',
                         'ADOLFO GONZALES CHAVES',
                         'BAHIA BLANCA',
                         'BENITO JUAREZ',
                         'CORONEL DE MARINA L. ROSALES',
                         'CORONEL DORREGO',
                         'CORONEL PRINGLES',
                         'CORONEL SUAREZ',
                         'CORONEL ROSALES',
                         'DAIREAUX',
                         'GENERAL LA MADRID',
                         'PARTIDO DE MONTE HERMOSO',
                         'GUAMINI',
                         'LAPRIDA',
                         'MONTE HERMOSO',
                         'PATAGONES',
                         'PELLEGRINI',
                         'PUAN',
                         'SAAVEDRA',
                         'SALLIQUELO',
                         'TORNQUIST',
                         'TRES ARROYOS',
                         'TRES LOMAS',
                         'VILLARINO'],
    'Sección Séptima': [   'AZUL',
                           'BOLIVAR',
                           'GENERAL ALVEAR',
                           'OLAVARRIA',
                           'ROQUE PEREZ',
                           'SALADILLO',
                           'TAPALQUE',
                           'VEINTICINCO DE MAYO'],
    'Sección Tercera': [   'ALMIRANTE BROWN',
                           'AVELLANEDA',
                           'BERAZATEGUI',
                           'BERISSO',
                           'BRANDSEN',
                           'CAÑUELAS',
                           'ENSENADA',
                           'ESTEBAN ECHEVERRIA',
                           'EZEIZA',
                           'FLORENCIO VARELA',
                           'LA MATANZA',
                           'LANUS',
                           'LOBOS',
                           'LOMAS DE ZAMORA',
                           'MAGDALENA',
                           'PRESIDENTE PERON',
                           'PUNTA INDIO',
                           'QUILMES',
                           'SAN VICENTE']}
