from pathlib import Path

PROJECT_PATH = Path(__file__).parents[1].resolve()  # Raiz del proyecto
UTILS_PATH = PROJECT_PATH / "utils"
DATA_PATH = UTILS_PATH / "data"  # Ruta donde se almacena los datos
SRC_PATH = PROJECT_PATH / "src"  # Ruta de funciones
STREAMLIT_PATH = PROJECT_PATH / "streamlit"  # App Streamlit

# BASES
BASE =  DATA_PATH / 'Base_Elecciones.zip'
ELECTORES_PATH = DATA_PATH / "ELECTORES.csv"

# Lista de municipios del AMBA (Provincia de Buenos Aires)
MUNICIPIOS_AMBA = [
    # Conurbano Bonaerense y zona metropolitana (sin incluir CABA)
    "ALMIRANTE BROWN",
    "AVELLANEDA",
    "BERAZATEGUI",
    "BERISSO",
    "BRANDSEN",
    "CAMPANA",
    "CAÑUELAS",
    "ENSENADA",
    "ESCOBAR",
    "ESTEBAN ECHEVERRIA",
    "EXALTACION DE LA CRUZ",
    "EZEIZA",
    "FLORENCIO VARELA",
    "GENERAL LAS HERAS",
    "GENERAL RODRIGUEZ",
    "GENERAL SAN MARTIN",
    "HURLINGHAM",
    "ITUZAINGO",
    "JOSE C. PAZ",
    "LA MATANZA",
    "LANUS",
    "LA PLATA",
    "LOMAS DE ZAMORA",
    "LUJAN",
    "MARCOS PAZ",
    "MALVINAS ARGENTINAS",
    "MERLO",
    "MORENO",
    "MORON",
    "PILAR",
    "PRESIDENTE PERON",
    "QUILMES",
    "SAN FERNANDO",
    "SAN ISIDRO",
    "SAN MIGUEL",
    "SAN VICENTE",
    "TIGRE",
    "TRES DE FEBRERO",
    "VICENTE LOPEZ",
    "ZARATE",
]

# Diccionario que asigna a cada sección sus municipios
SECCION_MUNICIPIOS = {   'Sección Capital': ['LA PLATA'],
    'Sección Cuarta': [   'ALBERTI',
                          'BRAGADO',
                          'CARLOS CASARES',
                          'CARLOS TEJEDOR',
                          'CHACABUCO',
                          'CHIVILCOY',
                          'FLORENTINO AMEGHINO',
                          'GENERAL ARENALES',
                          'GENERAL PINTO',
                          'GENERAL VIAMONTE',
                          'GENERAL VILLEGAS',
                          'HIPOLITO YRIGOYEN',
                          'JUNIN',
                          'LEANDRO N. ALEM',
                          'LINCOLN',
                          'NUEVE DE JULIO',
                          'PEHUAJO',
                          'RIVADAVIA',
                          'TRENQUE LAUQUEN'],
    'Sección Primera': [   'DEL PILAR',
                           'CAMPANA',
                           'ESCOBAR',
                           'GENERAL LAS HERAS',
                           'GENERAL RODRIGUEZ',
                           'GENERAL SAN MARTIN',
                           'HURLINGHAM',
                           'ITUZAINGO',
                           'JOSE C. PAZ',
                           'LUJAN',
                           'MALVINAS ARGENTINAS',
                           'MARCOS PAZ',
                           'MERCEDES',
                           'MERLO',
                           'MORENO',
                           'MORON',
                           'NAVARRO',
                           'PILAR',
                           'SAN FERNANDO',
                           'SAN ISIDRO',
                           'SAN MIGUEL',
                           'SUIPACHA',
                           'TIGRE',
                           'TRES DE FEBRERO',
                           'VICENTE LOPEZ'],
    'Sección Quinta': [   'PARTIDO DE VILLA GESELL',
                          'PARTIDO DE PINAMAR',
                          'PARTIDO DE LA COSTA',
                          'GENERAL MADARIAGA',
                          'AYACUCHO',
                          'BALCARCE',
                          'CASTELLI',
                          'CHASCOMUS',
                          'DOLORES',
                          'GENERAL ALVARADO',
                          'GENERAL BELGRANO',
                          'GENERAL GUIDO',
                          'GENERAL JUAN MADARIAGA',
                          'GENERAL LAVALLE',
                          'GENERAL PAZ',
                          'GENERAL PUEYRREDON',
                          'LA COSTA',
                          'LAS FLORES',
                          'LEZAMA',
                          'LOBERIA',
                          'MAIPU',
                          'MAR CHIQUITA',
                          'MONTE',
                          'NECOCHEA',
                          'PILA',
                          'PINAMAR',
                          'RAUCH',
                          'SAN CAYETANO',
                          'TANDIL',
                          'TORDILLO',
                          'VILLA GESELL'],
    'Sección Segunda': [   'ARRECIFES',
                           'BARADERO',
                           'CAPITAN SARMIENTO',
                           'CARMEN DE ARECO',
                           'COLON',
                           'EXALTACION DE LA CRUZ',
                           'PERGAMINO',
                           'RAMALLO',
                           'ROJAS',
                           'SALTO',
                           'SAN ANDRES DE GILES',
                           'SAN ANTONIO DE ARECO',
                           'SAN NICOLAS',
                           'SAN PEDRO',
                           'ZARATE'],
    'Sección Sexta': [   'ADOLFO ALSINA',
                         'ADOLFO GONZALES CHAVES',
                         'BAHIA BLANCA',
                         'BENITO JUAREZ',
                         'CORONEL DE MARINA L. ROSALES',
                         'CORONEL DORREGO',
                         'CORONEL PRINGLES',
                         'CORONEL SUAREZ',
                         'CORONEL ROSALES',
                         'DAIREAUX',
                         'GENERAL LA MADRID',
                         'PARTIDO DE MONTE HERMOSO',
                         'GUAMINI',
                         'LAPRIDA',
                         'MONTE HERMOSO',
                         'PATAGONES',
                         'PELLEGRINI',
                         'PUAN',
                         'SAAVEDRA',
                         'SALLIQUELO',
                         'TORNQUIST',
                         'TRES ARROYOS',
                         'TRES LOMAS',
                         'VILLARINO'],
    'Sección Séptima': [   'AZUL',
                           'BOLIVAR',
                           'GENERAL ALVEAR',
                           'OLAVARRIA',
                           'ROQUE PEREZ',
                           'SALADILLO',
                           'TAPALQUE',
                           'VEINTICINCO DE MAYO'],
    'Sección Tercera': [   'ALMIRANTE BROWN',
                           'AVELLANEDA',
                           'BERAZATEGUI',
                           'BERISSO',
                           'BRANDSEN',
                           'CAÑUELAS',
                           'ENSENADA',
                           'ESTEBAN ECHEVERRIA',
                           'EZEIZA',
                           'FLORENCIO VARELA',
                           'LA MATANZA',
                           'LANUS',
                           'LOBOS',
                           'LOMAS DE ZAMORA',
                           'MAGDALENA',
                           'PRESIDENTE PERON',
                           'PUNTA INDIO',
                           'QUILMES',
                           'SAN VICENTE']}

DISTRITOS = {
    1: "ADOLFO ALSINA",
    2: "ALBERTI",
    3: "ALMIRANTE BROWN",
    4: "AVELLANEDA",
    5: "AYACUCHO",
    6: "AZUL",
    7: "BAHIA BLANCA",
    8: "BALCARCE",
    9: "BARADERO",
    10: "ARRECIFES",
    11: "BERAZATEGUI",
    12: "BERISSO",
    13: "BOLIVAR",
    14: "BRAGADO",
    15: "BRANDSEN",
    16: "CAMPANA",
    17: "CAÑUELAS",
    18: "CAPITAN SARMIENTO",
    19: "CARLOS CASARES",
    20: "CARLOS TEJEDOR",
    21: "CARMEN DE ARECO",
    22: "PATAGONES",
    23: "CASTELLI",
    24: "COLON",
    25: "CORONEL DORREGO",
    26: "CORONEL PRINGLES",
    27: "CORONEL ROSALES",
    28: "CORONEL SUAREZ",
    29: "CHACABUCO",
    30: "CHASCOMUS",
    31: "CHIVILCOY",
    32: "DAIREAUX",
    33: "DOLORES",
    34: "ENSENADA",
    35: "ESCOBAR",
    36: "ESTEBAN ECHEVERRIA",
    37: "EXALTACION DE LA CRUZ",
    38: "FLORENCIO VARELA",
    39: "GENERAL ALVARADO",
    40: "GENERAL ALVEAR",
    41: "GENERAL ARENALES",
    42: "GENERAL BELGRANO",
    43: "GENERAL GUIDO",
    44: "GENERAL LA MADRID",
    45: "GENERAL LAS HERAS",
    46: "GENERAL LAVALLE",
    47: "GENERAL MADARIAGA",
    48: "GENERAL PAZ",
    49: "GENERAL PINTO",
    50: "GENERAL PUEYRREDON",
    51: "GENERAL RODRIGUEZ",
    52: "GENERAL SAN MARTIN",
    53: "SAN MIGUEL",
    54: "GENERAL VIAMONTE",
    55: "GENERAL VILLEGAS",
    56: "ADOLFO GONZALES CHAVES",
    57: "GUAMINI",
    58: "HIPOLITO YRIGOYEN",
    59: "BENITO JUAREZ",
    60: "JUNIN",
    61: "LA MATANZA",
    62: "LANUS",
    63: "LA PLATA",
    64: "LAPRIDA",
    65: "LAS FLORES",
    66: "LEANDRO N. ALEM",
    67: "LINCOLN",
    68: "LOBERIA",
    69: "LOBOS",
    70: "LOMAS DE ZAMORA",
    71: "LUJAN",
    72: "MAGDALENA",
    73: "MAIPU",
    74: "MAR CHIQUITA",
    75: "MARCOS PAZ",
    76: "MERCEDES",
    77: "MERLO",
    78: "MONTE",
    79: "MORENO",
    80: "MORON",
    81: "NAVARRO",
    82: "NECOCHEA",
    83: "NUEVE DE JULIO",
    84: "OLAVARRIA",
    85: "PEHUAJO",
    86: "PELLEGRINI",
    87: "PERGAMINO",
    88: "PILA",
    89: "DEL PILAR",
    90: "PARTIDO DE PINAMAR",
    91: "PUAN",
    92: "QUILMES",
    93: "RAMALLO",
    94: "RAUCH",
    95: "RIVADAVIA",
    96: "ROJAS",
    97: "ROQUE PEREZ",
    98: "SAAVEDRA",
    99: "SALADILLO",
    100: "SALLIQUELO",
    101: "SALTO",
    102: "SAN ANDRES DE GILES",
    103: "SAN ANTONIO DE ARECO",
    104: "SAN CAYETANO",
    105: "SAN FERNANDO",
    106: "SAN ISIDRO",
    107: "SAN NICOLAS",
    108: "SAN PEDRO",
    109: "SAN VICENTE",
    110: "SUIPACHA",
    111: "TANDIL",
    112: "TAPALQUE",
    113: "TIGRE",
    114: "TORNQUIST",
    115: "TRENQUE LAUQUEN",
    116: "TORDILLO",
    117: "TRES ARROYOS",
    118: "TRES DE FEBRERO",
    119: "PARTIDO DE LA COSTA",
    120: "PARTIDO DE MONTE HERMOSO",
    121: "VEINTICINCO DE MAYO",
    122: "VICENTE LOPEZ",
    123: "PARTIDO DE VILLA GESELL",
    124: "VILLARINO",
    125: "ZARATE",
    126: "TRES LOMAS",
    127: "FLORENTINO AMEGHINO",
    128: "PRESIDENTE PERON",
    129: "JOSE C. PAZ",
    130: "MALVINAS ARGENTINAS",
    131: "PUNTA INDIO",
    132: "EZEIZA",
    133: "ITUZAINGO",
    134: "HURLINGHAM",
    135: "LEZAMA",
}
